---
# defaults file for roles/kubernetes
baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
gpgkey_1: https://packages.cloud.google.com/yum/doc/yum-key.gpg
gpgkey_2: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
kubernetes_dir: /etc/yum.repos.d/
bridged_vals: 
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1

  - name: net.bridge.bridge-nf-call-iptables
    value: 1
kub_packages: 
  - kubelet 
  - kubeadm 
  - kubectl
